version: "3.9"

services:
  minio:
    image: minio/minio:latest
    container_name: cloud_ids_minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web Console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data: